version: "3.9"

services:

  # Vue.js
  vuejs:
    container_name: ${APP_NAME}-vuejs
    build:
      context: .
      dockerfile: docker/vue/Dockerfile 
    restart: unless-stopped
    ports:
      - "8070:8080"  
    volumes:
    - ./frontend:/app
    - /app/node_modules 
    networks:
      - redepadrao
    depends_on:
      - app  
    command:  npm run serve

  # PHP
  app:
    container_name: ${APP_NAME}-php
    build:
      context: ./
      dockerfile: docker/php/php.dockerfile
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./backend/:/var/www/api
    networks:
      redepadrao:
        ipv4_address: ${NGINX_IP}

  # NGINX
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine3.17
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./backend/:/var/www/api
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      redepadrao:
        ipv4_address: ${PHP_IP}
    depends_on:
      - app

networks:
  redepadrao:
    external: true
